import React, { useCallback, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useFocusEffect, useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { api } from "@/src/api";
import { useApp } from "@/src/store";
import { useI18n } from "@/src/i18n";
import { colors, fontSize, fonts, radius, spacing } from "@/src/theme";

export default function BodyScreen(){
 const {activeId}=useApp(); const {lang}=useI18n(); const ru=lang==="ru"; const router=useRouter(); const insets=useSafeAreaInsets();
 const [age,setAge]=useState<any>(null); const [systems,setSystems]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(false);
 const load=useCallback(async()=>{if(!activeId)return;setLoading(true);setError(false);try{const [a,s]=await Promise.all([api.biologicalAge(activeId),api.bodySystems(activeId)]);setAge(a);setSystems(s.systems||[])}catch{setError(true)}finally{setLoading(false)}},[activeId]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 return <ScrollView style={st.page} contentContainerStyle={[st.content,{paddingTop:insets.top+20,paddingBottom:insets.bottom+36}]}>
  <Pressable style={st.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={20} color={colors.onSurface}/></Pressable>
  <Text style={st.title}>{ru?"Организм":"Body"}</Text><Text style={st.sub}>{ru?"Только данные с источником. Если информации мало, Аида показывает недостаток данных вместо красивой выдуманной цифры.":"Only sourced data. When evidence is insufficient, Aida shows that instead of inventing a score."}</Text>
  {loading?<ActivityIndicator style={{marginTop:40}} color={colors.onSurface}/>:error?<State text={ru?"Не удалось загрузить данные":"Could not load data"}/>:<>
   <View style={st.ageCard}><Text style={st.label}>{ru?"Оценка биологического возраста":"Biological age estimate"}</Text>{age?.state==="data"?<><Text style={st.age}>{age.age}</Text><Text style={st.ageMeta}>{ru?`Хронологический: ${age.chronological_age}`:`Chronological: ${age.chronological_age}`}</Text><Text style={st.note}>{ru?"Это wellness-оценка по доступным измерениям, не медицинский диагноз.":"This is a wellness estimate from available measurements, not a medical diagnosis."}</Text><View style={st.factors}>{(age.factors||[]).map((f:any)=><View key={f.metric} style={st.factor}><Text style={st.factorName}>{f.metric}</Text><Text style={st.factorValue}>{String(f.value)}</Text></View>)}</View></>:<State text={ru?"Недостаточно данных для расчёта. Нужны дата рождения и минимум два поддерживаемых показателя.":"Not enough data. Date of birth and at least two supported measurements are required."}/>}</View>
   <Text style={st.sectionTitle}>{ru?"Системы организма":"Body systems"}</Text><View style={st.grid}>{systems.map((s:any)=><Pressable key={s.id} style={st.system}><View style={[st.dot,s.state==="data"&&st.dotData]}/><View style={{flex:1}}><Text style={st.systemName}>{s.label}</Text><Text style={st.systemMeta}>{s.state==="data"?(ru?`Есть данные · ${s.evidence_count}`:`Data available · ${s.evidence_count}`):(ru?"Нет данных":"No data")}</Text></View><Ionicons name="chevron-forward" size={16} color={colors.onSurfaceSecondary}/></Pressable>)}</View>
  </>}
 </ScrollView>
}
function State({text}:{text:string}){return <View style={st.state}><Ionicons name="information-circle-outline" size={20} color={colors.onSurfaceSecondary}/><Text style={st.stateText}>{text}</Text></View>}
const st=StyleSheet.create({page:{flex:1,backgroundColor:colors.surface},content:{width:"100%",maxWidth:900,alignSelf:"center",paddingHorizontal:spacing.xl},back:{width:42,height:42,borderRadius:21,backgroundColor:colors.surfaceSecondary,alignItems:"center",justifyContent:"center"},title:{fontSize:32,fontWeight:"800",fontFamily:fonts.display,color:colors.onSurface,marginTop:spacing.lg},sub:{fontSize:fontSize.base,lineHeight:22,color:colors.onSurfaceSecondary,marginTop:spacing.sm},ageCard:{marginTop:spacing.xl,padding:spacing.xl,borderRadius:radius.lg,backgroundColor:colors.surfaceSecondary,borderWidth:1,borderColor:colors.border},label:{fontSize:fontSize.sm,fontWeight:"700",color:colors.onSurfaceSecondary},age:{fontSize:62,lineHeight:68,fontWeight:"800",fontFamily:fonts.display,color:colors.onSurface,marginTop:4},ageMeta:{fontSize:fontSize.base,fontWeight:"700",color:colors.onSurface},note:{fontSize:fontSize.sm,lineHeight:19,color:colors.onSurfaceSecondary,marginTop:spacing.sm},factors:{flexDirection:"row",flexWrap:"wrap",gap:8,marginTop:spacing.lg},factor:{paddingHorizontal:12,paddingVertical:8,borderRadius:radius.pill,backgroundColor:colors.surface},factorName:{fontSize:11,color:colors.onSurfaceSecondary},factorValue:{fontSize:fontSize.base,fontWeight:"800",color:colors.onSurface},sectionTitle:{fontSize:fontSize.xl,fontWeight:"800",fontFamily:fonts.display,color:colors.onSurface,marginTop:spacing.xl,marginBottom:spacing.md},grid:{gap:spacing.md},system:{minHeight:68,padding:spacing.lg,borderRadius:radius.lg,backgroundColor:colors.surfaceSecondary,borderWidth:1,borderColor:colors.border,flexDirection:"row",alignItems:"center",gap:spacing.md},dot:{width:10,height:10,borderRadius:5,backgroundColor:colors.surfaceTertiary},dotData:{backgroundColor:colors.success},systemName:{fontSize:fontSize.base,fontWeight:"800",color:colors.onSurface},systemMeta:{fontSize:fontSize.sm,color:colors.onSurfaceSecondary,marginTop:3},state:{flexDirection:"row",gap:8,alignItems:"flex-start",marginTop:spacing.lg},stateText:{flex:1,color:colors.onSurfaceSecondary,lineHeight:20}});
