import React, { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { useFocusEffect, useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useApp } from "@/src/store";
import { useI18n } from "@/src/i18n";
import { cycleApi } from "@/src/cycleApi";
import { colors, fontSize, fonts, radius, spacing } from "@/src/theme";

function today(){return new Date().toISOString().slice(0,10)}

export default function CycleScreen(){
 const {activeId,activeProfile}=useApp(); const {lang}=useI18n(); const ru=lang==="ru"; const router=useRouter(); const insets=useSafeAreaInsets();
 const [data,setData]=useState<any>(null); const [forecast,setForecast]=useState<any>(null); const [loading,setLoading]=useState(true); const [date,setDate]=useState(today()); const [symptom,setSymptom]=useState(""); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null);
 const [cycleLength,setCycleLength]=useState(""); const [periodLength,setPeriodLength]=useState(""); const [reminders,setReminders]=useState(false); const [settingsSaved,setSettingsSaved]=useState(false);
 const load=useCallback(async()=>{if(!activeId)return;setLoading(true);setError(null);try{const [d,f]=await Promise.all([cycleApi.get(activeId),cycleApi.forecast(activeId)]);setData(d);setForecast(f);const settings=d?.settings||{};setCycleLength(settings.typical_cycle_length?String(settings.typical_cycle_length):"");setPeriodLength(settings.typical_period_length?String(settings.typical_period_length):"");setReminders(Boolean(settings.reminders_enabled))}catch(e:any){setError(e?.message||"error")}finally{setLoading(false)}},[activeId]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 useEffect(()=>{setSettingsSaved(false)},[cycleLength,periodLength,reminders]);
 const add=async(type:any,value?:string)=>{if(!activeId)return;setSaving(true);try{await cycleApi.addEvent({profile_id:activeId,event_type:type,observed_at:date,value:value||null});setSymptom("");await load()}finally{setSaving(false)}};
 const saveSettings=async()=>{if(!activeId)return;const c=cycleLength.trim()?Number(cycleLength):null;const p=periodLength.trim()?Number(periodLength):null;if(c!==null&&(c<15||c>60)){setError(ru?"Длина цикла должна быть от 15 до 60 дней":"Cycle length must be 15–60 days");return}if(p!==null&&(p<1||p>14)){setError(ru?"Длина менструации должна быть от 1 до 14 дней":"Period length must be 1–14 days");return}setSaving(true);setError(null);try{await cycleApi.saveSettings({profile_id:activeId,typical_cycle_length:c,typical_period_length:p,reminders_enabled:reminders});setSettingsSaved(true);await load()}catch(e:any){setError(e?.message||"error")}finally{setSaving(false)}};
 const starts=(data?.events||[]).filter((e:any)=>e.event_type==="period_start");
 return <ScrollView style={s.page} contentContainerStyle={[s.content,{paddingTop:insets.top+20,paddingBottom:insets.bottom+40}]} keyboardShouldPersistTaps="handled">
  <Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={20} color={colors.onSurface}/></Pressable>
  <Text style={s.title}>{ru?"Цикл":"Cycle"}</Text><Text style={s.sub}>{ru?`Данные относятся только к профилю «${activeProfile?.name||""}». Прогноз строится по вашей истории, а не по усреднённому циклу.`:`Data belongs only to “${activeProfile?.name||""}”. Forecasts use personal history, not a population default.`}</Text>
  {loading?<ActivityIndicator style={{marginTop:40}} color={colors.onSurface}/>:error?<Text style={s.error}>{error}</Text>:<>
   <View style={s.card}><Text style={s.label}>{ru?"Сегодня":"Today"}</Text>{forecast?.state==="data"?<><Text style={s.big}>{ru?`${forecast.cycle_day}-й день`:`Day ${forecast.cycle_day}`}</Text><Text style={s.meta}>{ru?`Следующая менструация ориентировочно ${forecast.estimated_next_start}`:`Next period estimated around ${forecast.estimated_next_start}`}</Text><Text style={s.note}>{ru?`Окно неопределённости: ${forecast.window_start} — ${forecast.window_end}. Основание: ${forecast.basis==="personal_history"?"ваша история":"ваши настройки"}.`:`Uncertainty window: ${forecast.window_start} — ${forecast.window_end}. Basis: ${forecast.basis}.`}</Text><Text style={s.disclaimer}>{forecast.disclaimer}</Text></>:<><Text style={s.big}>{ru?"Недостаточно данных":"Not enough data"}</Text><Text style={s.note}>{ru?"Добавьте даты начала нескольких циклов или задайте свою типичную длину цикла ниже. Аида не подставляет «28 дней» автоматически.":"Add several period-start dates or your own typical cycle length below. Aida does not silently assume 28 days."}</Text></>}</View>
   <View style={s.card}><Text style={s.cardTitle}>{ru?"Мои настройки":"My settings"}</Text><Text style={s.note}>{ru?"Эти значения — ваши исходные данные. Они не заменяют личную историю и могут быть изменены в любой момент.":"These are your own baseline values. They do not replace personal history and can be changed anytime."}</Text><TextInput value={cycleLength} onChangeText={setCycleLength} keyboardType="number-pad" placeholder={ru?"Типичная длина цикла, дней":"Typical cycle length, days"} placeholderTextColor={colors.onSurfaceSecondary} style={[s.input,{marginTop:spacing.md}]}/><TextInput value={periodLength} onChangeText={setPeriodLength} keyboardType="number-pad" placeholder={ru?"Типичная длительность менструации, дней":"Typical period length, days"} placeholderTextColor={colors.onSurfaceSecondary} style={[s.input,{marginTop:spacing.sm}]}/><View style={s.switchRow}><View style={{flex:1}}><Text style={s.switchTitle}>{ru?"Мягкие напоминания":"Gentle reminders"}</Text><Text style={s.note}>{ru?"Напоминать о прогнозном окне начала менструации, когда данных достаточно.":"Remind me about the predicted period window when there is enough data."}</Text></View><Switch value={reminders} onValueChange={setReminders}/></View><Pressable style={s.button} onPress={saveSettings} disabled={saving}>{saving?<ActivityIndicator color={colors.onSurfaceInverse}/>:<Text style={s.buttonText}>{settingsSaved?(ru?"Сохранено":"Saved"):(ru?"Сохранить настройки":"Save settings")}</Text>}</Pressable></View>
   <View style={s.card}><Text style={s.cardTitle}>{ru?"Добавить событие":"Add event"}</Text><TextInput value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" placeholderTextColor={colors.onSurfaceSecondary} style={s.input}/><View style={s.row}><Pressable style={s.action} onPress={()=>add("period_start")} disabled={saving}><Text style={s.actionText}>{ru?"Начало менструации":"Period start"}</Text></Pressable><Pressable style={s.action} onPress={()=>add("period_end")} disabled={saving}><Text style={s.actionText}>{ru?"Конец":"Period end"}</Text></Pressable></View><TextInput value={symptom} onChangeText={setSymptom} placeholder={ru?"Симптом или заметка":"Symptom or note"} placeholderTextColor={colors.onSurfaceSecondary} style={[s.input,{marginTop:spacing.md}]}/><Pressable style={[s.button,!symptom.trim()&&{opacity:.45}]} disabled={!symptom.trim()||saving} onPress={()=>add("symptom",symptom.trim())}>{saving?<ActivityIndicator color={colors.onSurfaceInverse}/>:<Text style={s.buttonText}>{ru?"Сохранить симптом":"Save symptom"}</Text>}</Pressable></View>
   <Text style={s.section}>{ru?"История":"History"}</Text>{starts.length===0?<View style={s.empty}><Text style={s.note}>{ru?"Пока нет отмеченных начал цикла.":"No period starts logged yet."}</Text></View>:starts.slice(0,12).map((e:any)=><View key={e.id} style={s.event}><View style={s.dot}/><View><Text style={s.eventTitle}>{ru?"Начало менструации":"Period start"}</Text><Text style={s.meta}>{String(e.observed_at).slice(0,10)}</Text></View></View>)}
  </>}
 </ScrollView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.surface},content:{width:"100%",maxWidth:760,alignSelf:"center",paddingHorizontal:spacing.xl},back:{width:42,height:42,borderRadius:21,backgroundColor:colors.surfaceSecondary,alignItems:"center",justifyContent:"center"},title:{fontSize:32,fontWeight:"800",fontFamily:fonts.display,color:colors.onSurface,marginTop:spacing.lg},sub:{fontSize:fontSize.base,lineHeight:22,color:colors.onSurfaceSecondary,marginTop:spacing.sm},card:{marginTop:spacing.xl,padding:spacing.lg,borderRadius:radius.lg,backgroundColor:colors.surfaceSecondary,borderWidth:1,borderColor:colors.border},label:{fontSize:fontSize.sm,fontWeight:"700",color:colors.onSurfaceSecondary},big:{fontSize:30,fontWeight:"800",fontFamily:fonts.display,color:colors.onSurface,marginTop:4},meta:{fontSize:fontSize.sm,color:colors.onSurfaceSecondary,marginTop:4},note:{fontSize:fontSize.sm,lineHeight:19,color:colors.onSurfaceSecondary,marginTop:spacing.sm},disclaimer:{fontSize:12,lineHeight:17,color:colors.onSurfaceSecondary,marginTop:spacing.md},cardTitle:{fontSize:fontSize.lg,fontWeight:"800",fontFamily:fonts.display,color:colors.onSurface,marginBottom:spacing.md},input:{minHeight:50,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,paddingHorizontal:spacing.md,color:colors.onSurface},row:{flexDirection:"row",gap:8,marginTop:spacing.md},action:{flex:1,minHeight:46,borderRadius:radius.pill,backgroundColor:colors.surface,alignItems:"center",justifyContent:"center",paddingHorizontal:10},actionText:{fontWeight:"700",color:colors.onSurface,textAlign:"center"},button:{minHeight:48,borderRadius:radius.pill,backgroundColor:colors.onSurface,alignItems:"center",justifyContent:"center",marginTop:spacing.md},buttonText:{color:colors.onSurfaceInverse,fontWeight:"800"},switchRow:{flexDirection:"row",alignItems:"center",gap:spacing.md,marginTop:spacing.md},switchTitle:{fontSize:fontSize.base,fontWeight:"800",color:colors.onSurface},section:{fontSize:fontSize.xl,fontWeight:"800",fontFamily:fonts.display,color:colors.onSurface,marginTop:spacing.xl,marginBottom:spacing.md},empty:{padding:spacing.lg,borderRadius:radius.lg,backgroundColor:colors.surfaceSecondary},event:{minHeight:64,flexDirection:"row",alignItems:"center",gap:spacing.md,borderBottomWidth:1,borderBottomColor:colors.divider},dot:{width:10,height:10,borderRadius:5,backgroundColor:colors.onSurface},eventTitle:{fontWeight:"800",color:colors.onSurface},error:{marginTop:spacing.xl,color:colors.error}});
