import React, { useCallback, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect, useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { api } from "@/src/api";
import { useApp } from "@/src/store";
import { useI18n } from "@/src/i18n";
import { colors, fontSize, fonts, radius, spacing } from "@/src/theme";

export default function FamilyScreen(){
 const {activeId,activeProfile}=useApp(); const {lang}=useI18n(); const ru=lang==="ru"; const router=useRouter(); const insets=useSafeAreaInsets();
 const [items,setItems]=useState<any[]>([]); const [email,setEmail]=useState(""); const [role,setRole]=useState<"viewer"|"editor">("viewer"); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!activeId)return;try{const data=await api.familyAccess(activeId);setItems(data.access||[])}catch{setItems([])}},[activeId]); useFocusEffect(useCallback(()=>{load()},[load]));
 const share=async()=>{if(!activeId||!email.trim())return;setBusy(true);setError(null);try{await api.shareProfile(activeId,email.trim(),role);setEmail("");await load()}catch(e:any){setError(ru?"Не удалось выдать доступ. У пользователя должен быть аккаунт Аиды.":"Could not grant access. The recipient needs an Aida account.")}finally{setBusy(false)}};
 const revoke=async(id:string)=>{if(!activeId)return;await api.revokeShare(activeId,id);await load()};
 return <ScrollView style={s.page} contentContainerStyle={[s.content,{paddingTop:insets.top+20,paddingBottom:insets.bottom+36}]} keyboardShouldPersistTaps="handled">
  <Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={20} color={colors.onSurface}/></Pressable><Text style={s.title}>{ru?"Семья и доступ":"Family & access"}</Text><Text style={s.sub}>{ru?`Кто может видеть данные профиля «${activeProfile?.name||""}». Доступ закрыт по умолчанию.`:`Who can access “${activeProfile?.name||""}”. Access is denied by default.`}</Text>
  <View style={s.card}><Text style={s.cardTitle}>{ru?"Дать доступ":"Share profile"}</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="email@example.com" placeholderTextColor={colors.onSurfaceSecondary} style={s.input}/><View style={s.roles}><Pressable style={[s.role,role==="viewer"&&s.roleOn]} onPress={()=>setRole("viewer")}><Text style={[s.roleText,role==="viewer"&&s.roleTextOn]}>{ru?"Только просмотр":"View only"}</Text></Pressable><Pressable style={[s.role,role==="editor"&&s.roleOn]} onPress={()=>setRole("editor")}><Text style={[s.roleText,role==="editor"&&s.roleTextOn]}>{ru?"Можно редактировать":"Can edit"}</Text></Pressable></View>{error?<Text style={s.error}>{error}</Text>:null}<Pressable style={s.button} onPress={share} disabled={busy}>{busy?<ActivityIndicator color={colors.onSurfaceInverse}/>:<Text style={s.buttonText}>{ru?"Добавить":"Add access"}</Text>}</Pressable></View>
  <Text style={s.section}>{ru?"Текущий доступ":"Current access"}</Text>{items.length===0?<View style={s.empty}><Text style={s.emptyText}>{ru?"Пока профиль никому не открыт.":"This profile is not shared yet."}</Text></View>:items.map((item:any)=><View key={item.id} style={s.person}><View style={s.avatar}><Ionicons name={item.role==="owner"?"person":"people"} size={18} color={colors.onSurface}/></View><View style={{flex:1}}><Text style={s.personName}>{item.name||item.email||item.account_id}</Text><Text style={s.meta}>{item.role==="owner"?(ru?"Владелец":"Owner"):item.role==="editor"?(ru?"Редактор":"Editor"):(ru?"Просмотр":"Viewer")}</Text></View>{item.role!=="owner"?<Pressable style={s.remove} onPress={()=>revoke(item.id)}><Ionicons name="close" size={18} color={colors.error}/></Pressable>:null}</View>)}
 </ScrollView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.surface},content:{width:"100%",maxWidth:760,alignSelf:"center",paddingHorizontal:spacing.xl},back:{width:42,height:42,borderRadius:21,backgroundColor:colors.surfaceSecondary,alignItems:"center",justifyContent:"center"},title:{fontSize:32,fontWeight:"800",fontFamily:fonts.display,color:colors.onSurface,marginTop:spacing.lg},sub:{fontSize:fontSize.base,lineHeight:22,color:colors.onSurfaceSecondary,marginTop:spacing.sm},card:{marginTop:spacing.xl,padding:spacing.lg,backgroundColor:colors.surfaceSecondary,borderRadius:radius.lg,borderWidth:1,borderColor:colors.border},cardTitle:{fontSize:fontSize.lg,fontWeight:"800",fontFamily:fonts.display,color:colors.onSurface,marginBottom:spacing.md},input:{minHeight:50,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,paddingHorizontal:spacing.md,color:colors.onSurface},roles:{flexDirection:"row",gap:8,marginTop:spacing.md,flexWrap:"wrap"},role:{paddingHorizontal:14,paddingVertical:9,borderRadius:radius.pill,backgroundColor:colors.surface},roleOn:{backgroundColor:colors.onSurface},roleText:{fontWeight:"700",color:colors.onSurface},roleTextOn:{color:colors.onSurfaceInverse},error:{color:colors.error,fontSize:fontSize.sm,marginTop:spacing.md},button:{minHeight:48,borderRadius:radius.pill,backgroundColor:colors.onSurface,alignItems:"center",justifyContent:"center",marginTop:spacing.lg},buttonText:{color:colors.onSurfaceInverse,fontWeight:"800"},section:{fontSize:fontSize.xl,fontWeight:"800",fontFamily:fonts.display,color:colors.onSurface,marginTop:spacing.xl,marginBottom:spacing.md},person:{minHeight:68,backgroundColor:colors.surfaceSecondary,borderRadius:radius.lg,borderWidth:1,borderColor:colors.border,padding:spacing.md,flexDirection:"row",alignItems:"center",gap:spacing.md,marginBottom:spacing.sm},avatar:{width:40,height:40,borderRadius:20,backgroundColor:colors.surface,alignItems:"center",justifyContent:"center"},personName:{fontWeight:"800",fontSize:fontSize.base,color:colors.onSurface},meta:{fontSize:fontSize.sm,color:colors.onSurfaceSecondary,marginTop:2},remove:{width:36,height:36,borderRadius:18,backgroundColor:colors.surface,alignItems:"center",justifyContent:"center"},empty:{padding:spacing.lg,backgroundColor:colors.surfaceSecondary,borderRadius:radius.lg},emptyText:{color:colors.onSurfaceSecondary}});
