import React, { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useFocusEffect, useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { useApp } from "@/src/store";
import { useI18n } from "@/src/i18n";
import { api, LabTest, Medication, Symptom } from "@/src/api";
import { Txt } from "@/src/emergent/ui";
import { FCard, figma, mobileStyles, RoundIcon, SectionHeader } from "@/src/emergent/figma-mobile";

type Entry = { type:"lab";date:string;data:LabTest }|{type:"symptom";date:string;data:Symptom}|{type:"med";date:string;data:Medication};
type Filter="all"|"symptoms"|"labs"|"medications";
const FILTERS:Filter[]=["all","symptoms","labs","medications"];

export default function TimelineScreen(){
 const insets=useSafeAreaInsets();const router=useRouter();const{activeId,refreshTick,bumpRefresh}=useApp();const{lang}=useI18n();const[loading,setLoading]=useState(true);const[error,setError]=useState(false);const[refreshing,setRefreshing]=useState(false);const[labs,setLabs]=useState<LabTest[]>([]);const[symptoms,setSymptoms]=useState<Symptom[]>([]);const[meds,setMeds]=useState<Medication[]>([]);const[filter,setFilter]=useState<Filter>("all");
 const load=useCallback(async()=>{if(!activeId){setLabs([]);setSymptoms([]);setMeds([]);setLoading(false);return;}setError(false);try{const[l,s,m]=await Promise.all([api.listLabs(activeId),api.listSymptoms(activeId),api.listMeds(activeId)]);setLabs(l);setSymptoms(s);setMeds(m);}catch{setError(true);}finally{setLoading(false);}},[activeId]);
 useFocusEffect(useCallback(()=>{setLoading(true);void load();},[load,refreshTick]));
 const entries:Entry[]=useMemo(()=>{const list:Entry[]=[];if(filter==="all"||filter==="labs")labs.forEach(d=>list.push({type:"lab",date:d.date,data:d}));if(filter==="all"||filter==="symptoms")symptoms.forEach(d=>list.push({type:"symptom",date:d.date,data:d}));if(filter==="all"||filter==="medications")meds.forEach(d=>list.push({type:"med",date:d.start_date||d.date||"",data:d}));return list.sort((a,b)=>a.date<b.date?1:-1);},[filter,labs,symptoms,meds]);
 const improvements=Math.max(0,labs.filter(l=>l.biomarkers.every(b=>b.status!=="high"&&b.status!=="low")).length);const warnings=labs.reduce((n,l)=>n+l.biomarkers.filter(b=>b.status==="high"||b.status==="low").length,0);const stable=Math.max(0,entries.length-warnings);
 const del=async(entry:Entry)=>{if(entry.type==="lab")await api.deleteLab(entry.data.id);else if(entry.type==="symptom")await api.deleteSymptom(entry.data.id);else await api.deleteMed(entry.data.id);bumpRefresh();};
 return <View style={mobileStyles.page}><ScrollView showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={async()=>{setRefreshing(true);await load();setRefreshing(false);}} tintColor={figma.ink}/>} contentContainerStyle={{paddingTop:insets.top+14,paddingBottom:36}}><View style={mobileStyles.content}>
   <View style={styles.head}><View><Txt variant="h1" style={styles.title}>{lang==="ru"?"Изменения":"Changes"}</Txt><Txt variant="caption" color={figma.muted} style={{marginTop:4,maxWidth:300}}>{lang==="ru"?"Отслеживайте важные изменения в состоянии, анализах и симптомах":"Track important changes in your state, labs and symptoms"}</Txt></View><Pressable onPress={()=>router.push("/(tabs)/health" as any)}><RoundIcon icon="add" size={48} bg={figma.card}/></Pressable></View>
   <View style={styles.tabs}>{FILTERS.map(f=><Pressable key={f} onPress={()=>setFilter(f)} style={[styles.tab,filter===f&&styles.tabActive]}><Txt variant="label" weight="bold" color={filter===f?"#fff":figma.muted}>{filterLabel(f,lang)}</Txt></Pressable>)}</View>
   {loading?<View style={styles.state}><ActivityIndicator color={figma.ink}/></View>:!activeId?<State icon="person-circle-outline" title={lang==="ru"?"Выберите профиль":"Choose a profile"}/>:error?<State icon="cloud-offline-outline" title={lang==="ru"?"Не удалось загрузить историю":"Could not load history"} action={load}/>:<>
    <FCard style={styles.month}><Txt variant="h2">{lang==="ru"?"За последний месяц":"Last month"}</Txt><View style={styles.stats}><Stat icon="trending-up-outline" value={improvements} label={lang==="ru"?"Улучшений":"Improved"} bg="#EAF5DD"/><Stat icon="trending-down-outline" value={warnings} label={lang==="ru"?"Требуют внимания":"Attention"} bg="#FBEAE5"/><Stat icon="analytics-outline" value={stable} label={lang==="ru"?"Стабильно":"Stable"} bg="#EAF2FA"/><Stat icon="list-outline" value={entries.length} label={lang==="ru"?"Всего записей":"Total"} bg="#FFF6D8"/></View></FCard>
    <SectionHeader title={lang==="ru"?"Динамика состояния":"State dynamics"} action={lang==="ru"?"Подробнее ›":"Details ›"}/><FCard style={styles.chart}><View style={styles.chartBands}><View style={[styles.band,{backgroundColor:"#F1FAD0"}]}/><View style={[styles.band,{backgroundColor:"#FFF6D8"}]}/><View style={[styles.band,{backgroundColor:"#FBEAE5"}]}/></View><View style={styles.points}>{[72,60,64,48,55,38].map((v,i)=><View key={i} style={[styles.point,{bottom:v}]}/>)}</View><View style={styles.chartLabels}><Txt variant="label" color={figma.muted}>{lang==="ru"?"раньше":"earlier"}</Txt><Txt variant="label" color={figma.muted}>{lang==="ru"?"сейчас":"now"}</Txt></View></FCard>
    <SectionHeader title={lang==="ru"?"Последние изменения":"Recent changes"} action={`${entries.length}`}/>
    <FCard style={{paddingVertical:4}}>{entries.length?entries.slice(0,10).map((entry,i)=><View key={`${entry.type}-${entry.data.id}`}>{i?<View style={mobileStyles.divider}/>:null}<Pressable onLongPress={()=>void del(entry)} style={styles.entry}><RoundIcon icon={entry.type==="lab"?"flask-outline":entry.type==="symptom"?"pulse-outline":"medkit-outline"} size={46} bg={entry.type==="lab"?"#FFF6D8":entry.type==="symptom"?"#FBEAE5":"#EAF2FA"}/><View style={{flex:1}}><Txt variant="caption" weight="bold">{entryTitle(entry,lang)}</Txt><Txt variant="label" color={figma.muted} numberOfLines={2}>{entrySub(entry,lang)}</Txt><Txt variant="label" color={figma.muted} style={{marginTop:3}}>{entry.date||"—"}</Txt></View><Ionicons name="chevron-forward" size={19} color={figma.muted}/></Pressable></View>):<View style={styles.empty}><Ionicons name="sparkles-outline" size={30} color={figma.muted}/><Txt variant="caption" weight="bold">{lang==="ru"?"Пока нет изменений":"No changes yet"}</Txt><Txt variant="label" color={figma.muted}>{lang==="ru"?"Добавляйте данные — история появится здесь":"Add data and your timeline will appear here"}</Txt></View>}</FCard>
   </>}
 </View></ScrollView></View>;
}
function Stat({icon,value,label,bg}:{icon:keyof typeof Ionicons.glyphMap;value:number;label:string;bg:string}){return <View style={styles.stat}><RoundIcon icon={icon} size={38} bg={bg}/><Txt variant="h1" style={{fontSize:30}}>{value}</Txt><Txt variant="label" color={figma.muted} style={{textAlign:"center"}}>{label}</Txt></View>}
function State({icon,title,action}:{icon:keyof typeof Ionicons.glyphMap;title:string;action?:()=>void}){return <View style={styles.state}><Ionicons name={icon} size={38} color={figma.muted}/><Txt variant="h2">{title}</Txt>{action?<Pressable onPress={action} style={styles.retry}><Txt variant="caption" color="#fff" weight="bold">Повторить</Txt></Pressable>:null}</View>}
function filterLabel(f:Filter,lang:string){const ru:any={all:"Обзор",symptoms:"Симптомы",labs:"Анализы",medications:"Лекарства"};const en:any={all:"Overview",symptoms:"Symptoms",labs:"Labs",medications:"Meds"};return(lang==="ru"?ru:en)[f]}
function entryTitle(e:Entry,lang:string){if(e.type==="lab")return e.data.title|| (lang==="ru"?"Анализ":"Lab");if(e.type==="symptom")return e.data.name;return e.data.name|| (lang==="ru"?"Лекарство":"Medication")}
function entrySub(e:Entry,lang:string){if(e.type==="lab"){const n=e.data.biomarkers.filter(b=>b.status==="high"||b.status==="low").length;return n?`${n} ${lang==="ru"?"показателя вне референса":"markers out of range"}`:`${e.data.biomarkers.length} ${lang==="ru"?"показателей":"markers"}`;}if(e.type==="symptom")return `${lang==="ru"?"Выраженность":"Severity"}: ${e.data.severity}/10`;return [e.data.dose,e.data.schedule].filter(Boolean).join(" · ")|| (lang==="ru"?"Схема приёма":"Medication schedule")}
const styles=StyleSheet.create({head:{flexDirection:"row",alignItems:"flex-start",justifyContent:"space-between"},title:{fontSize:38,lineHeight:42},tabs:{height:54,borderRadius:27,backgroundColor:figma.card,padding:4,flexDirection:"row",marginTop:18},tab:{flex:1,borderRadius:23,alignItems:"center",justifyContent:"center"},tabActive:{backgroundColor:figma.ink},month:{minHeight:250,marginTop:16},stats:{flexDirection:"row",justifyContent:"space-between",marginTop:20},stat:{width:"24%",alignItems:"center",gap:8},chart:{height:310,position:"relative",overflow:"hidden"},chartBands:{position:"absolute",left:16,right:16,top:58,bottom:48,gap:0},band:{flex:1,opacity:.65},points:{position:"absolute",left:35,right:35,bottom:58,height:150,flexDirection:"row",alignItems:"flex-end",justifyContent:"space-between"},point:{width:13,height:13,borderRadius:7,backgroundColor:figma.ink},chartLabels:{position:"absolute",left:16,right:16,bottom:18,flexDirection:"row",justifyContent:"space-between"},entry:{minHeight:108,flexDirection:"row",alignItems:"center",gap:14},empty:{minHeight:150,alignItems:"center",justifyContent:"center",gap:8},state:{minHeight:420,alignItems:"center",justifyContent:"center",gap:10},retry:{height:44,borderRadius:999,backgroundColor:figma.ink,paddingHorizontal:18,alignItems:"center",justifyContent:"center"}});
