import React, { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, TextInput, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useFocusEffect, useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import dayjs from "dayjs";

import { Sheet } from "@/src/components/Sheet";
import { useApp } from "@/src/store";
import { useI18n } from "@/src/i18n";
import { api, Medication } from "@/src/api";
import { getMedicationDay, markMedicationIntake, MedicationSlot, updateMedicationSchedule } from "@/src/medicationScheduleApi";
import { Txt } from "@/src/emergent/ui";
import { AddCard, FCard, figma, gradients, GradientPanel, mobileStyles, SectionHeader } from "@/src/emergent/figma-mobile";

type RichMedication = Medication & { times?: string[]; meal_relation?: string; active?: boolean };
const TIME_RE = /^(?:[01]\d|2[0-3]):[0-5]\d$/;
function localDateString(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;}
function parseTimes(value:string){return [...new Set(value.split(/[;,\s]+/).map(x=>x.trim()).filter(Boolean))].sort();}

export default function MedicationsScreen(){
  const insets=useSafeAreaInsets(); const router=useRouter(); const {activeId,refreshTick,bumpRefresh}=useApp(); const {lang}=useI18n();
  const [items,setItems]=useState<RichMedication[]>([]); const [slots,setSlots]=useState<MedicationSlot[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(false);
  const [editorOpen,setEditorOpen]=useState(false); const [editingId,setEditingId]=useState<string|null>(null); const [name,setName]=useState(""); const [dose,setDose]=useState(""); const [timesText,setTimesText]=useState(""); const [meal,setMeal]=useState("any"); const [saving,setSaving]=useState(false); const [marking,setMarking]=useState<string|null>(null);
  const today=localDateString();
  const load=useCallback(async()=>{if(!activeId){setItems([]);setSlots([]);setLoading(false);return;} setError(false); try{const [meds,day]=await Promise.all([api.listMeds(activeId),getMedicationDay(activeId,today)]);setItems(meds as RichMedication[]);setSlots(day.slots||[]);}catch{setError(true);}finally{setLoading(false);}},[activeId,today]);
  useFocusEffect(useCallback(()=>{setLoading(true);void load();},[load,refreshTick]));
  const reset=()=>{setEditingId(null);setName("");setDose("");setTimesText("");setMeal("any");};
  const openAdd=()=>{reset();setEditorOpen(true);};
  const openEdit=(m:RichMedication)=>{setEditingId(m.id);setName(m.name||"");setDose(m.dose||"");setTimesText((m.times||[]).join(", "));setMeal(m.meal_relation||"any");setEditorOpen(true);};
  const save=async()=>{if(!activeId||!name.trim())return;const times=parseTimes(timesText);if(times.some(t=>!TIME_RE.test(t)))return;setSaving(true);try{const payload={name:name.trim(),dose:dose.trim()||null,times,meal_relation:meal,schedule:times.length?times.join(", "):null};if(editingId)await updateMedicationSchedule(editingId,payload);else await api.createMed({profile_id:activeId,...payload,active:true,start_date:today,source:"aida"});setEditorOpen(false);reset();await load();bumpRefresh();}finally{setSaving(false);}};
  const del=async(id:string)=>{setItems(prev=>prev.filter(x=>x.id!==id));await api.deleteMed(id).catch(()=>{});bumpRefresh();};
  const mark=async(slot:MedicationSlot,status:"taken"|"skipped")=>{setMarking(slot.id);try{await markMedicationIntake(slot.medication_id,slot.scheduled_at,status);await load();bumpRefresh();}finally{setMarking(null);}};
  const pending=slots.filter(s=>s.status==="pending"); const taken=slots.filter(s=>s.status==="taken"); const active=items.filter(m=>m.active!==false);
  const nearest=pending[0] as any;
  const adherence=slots.length?Math.round((taken.length/slots.length)*100):null;
  const nextTime=nearest?.scheduled_at?dayjs(nearest.scheduled_at).format("HH:mm"):((active[0]?.times||[])[0]||"—");
  const nextMed=nearest ? items.find(m=>m.id===nearest.medication_id) : active[0];
  const weekBars=useMemo(()=>[88,100,82,100,94,100,88],[]);

  return <View style={mobileStyles.page}>
    <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{paddingTop:insets.top+12,paddingBottom:36}}><View style={mobileStyles.content}>
      <View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.round}><Ionicons name="chevron-back" size={22} color={figma.ink}/></Pressable><View style={{flex:1}}><Txt variant="h1" style={styles.title}>{lang==="ru"?"Лекарства":"Medications"}</Txt><Txt variant="label" color={figma.muted}>{lang==="ru"?"Расписание, приём и напоминания":"Schedule, intake and reminders"}</Txt></View><Pressable onPress={openAdd} style={styles.round}><Ionicons name="add" size={23} color={figma.ink}/></Pressable></View>
      <View style={{marginTop:18}}><AddCard testID="add-med-button" title={lang==="ru"?"Добавить лекарство":"Add medication"} subtitle={lang==="ru"?"Препарат · дозировка · расписание":"Medicine · dose · schedule"} icon="medkit-outline" onPress={openAdd}/></View>

      {loading?<View style={styles.loading}><ActivityIndicator color={figma.ink}/><Txt variant="label" color={figma.muted}>{lang==="ru"?"Обновляем лекарства…":"Refreshing medications…"}</Txt></View>:null}
      {error?<Pressable onPress={load} style={styles.error}><Ionicons name="cloud-offline-outline" size={18} color={figma.muted}/><Txt variant="label" color={figma.muted} style={{flex:1}}>{lang==="ru"?"Часть данных не обновилась":"Some data did not refresh"}</Txt><Txt variant="label" weight="bold">{lang==="ru"?"Повторить":"Retry"}</Txt></Pressable>:null}

      <View style={{marginTop:18}}><GradientPanel colors={gradients.meds} style={styles.hero}><Txt variant="label" color={figma.soft} weight="bold">{lang==="ru"?"БЛИЖАЙШИЙ ПРИЁМ":"NEXT DOSE"}</Txt><Txt variant="display" style={styles.time}>{nextTime}</Txt><Txt variant="h3" style={{marginTop:2}}>{nextMed?.name || (lang==="ru"?"Нет запланированных приёмов":"No scheduled doses")}</Txt><Txt variant="label" color={figma.soft} style={{marginTop:4}}>{nextMed?.dose || ""}{nextMed?.meal_relation&&nextMed.meal_relation!=="any"?` · ${mealLabel(nextMed.meal_relation,lang)}`:""}</Txt>{nearest?<Pressable disabled={marking===nearest.id} onPress={()=>mark(nearest,"taken")} style={styles.heroAction}><Txt variant="label" weight="bold">{marking===nearest.id?"…":(lang==="ru"?"Принять":"Take")}</Txt></Pressable>:null}<View style={styles.sun}><Ionicons name="sunny-outline" size={25} color={figma.ink}/><Txt variant="label" color={figma.muted}>{lang==="ru"?"сегодня":"today"}</Txt></View></GradientPanel></View>

      <SectionHeader title={lang==="ru"?"Сегодня":"Today"} action={`${slots.length} ${lang==="ru"?"приёма":"doses"}`}/>
      <View style={styles.todayStack}>{slots.length?slots.map((slot:any)=><FCard key={slot.id} style={styles.slot}><View style={styles.timePill}><Txt variant="label" weight="bold">{dayjs(slot.scheduled_at).format("HH:mm")}</Txt></View><View style={{flex:1}}><Txt variant="caption" weight="bold">{items.find(m=>m.id===slot.medication_id)?.name || slot.medication_name || (lang==="ru"?"Препарат":"Medication")}</Txt><Txt variant="label" color={figma.muted}>{items.find(m=>m.id===slot.medication_id)?.dose||""}</Txt></View><View style={{alignItems:"flex-end",gap:8}}><Txt variant="label" color={slot.status==="taken"?figma.green:figma.muted}>{slot.status==="taken"?(lang==="ru"?"Принято":"Taken"):slot.status==="skipped"?(lang==="ru"?"Пропущено":"Skipped"):(lang==="ru"?"Следующий":"Next")}</Txt>{slot.status==="pending"?<Pressable onPress={()=>mark(slot,"taken")} style={styles.smallAction}><Txt variant="label" weight="bold">{lang==="ru"?"Принять":"Take"}</Txt></Pressable>:<Ionicons name={slot.status==="taken"?"checkmark-circle":"remove-circle-outline"} size={24} color={slot.status==="taken"?figma.green:figma.muted}/>}</View></FCard>):<FCard><Txt variant="label" color={figma.muted}>{lang==="ru"?"На сегодня приёмов нет":"No doses today"}</Txt></FCard>}</View>

      <SectionHeader title={lang==="ru"?"Соблюдение схемы":"Adherence"} action={lang==="ru"?"Последние 7 дней":"Last 7 days"}/>
      <FCard style={styles.adherence}><View style={styles.adHead}><View><Txt variant="display" style={styles.percent}>{adherence!=null?`${adherence}%`:"—"}</Txt><Txt variant="label" color={figma.muted}>{lang==="ru"?"приёмов вовремя":"taken on time"}</Txt></View><View style={[mobileStyles.pill,{backgroundColor:"#EEF2DB"}]}><Txt variant="label" weight="bold">{taken.length} {lang==="ru"?"из":"of"} {slots.length}</Txt></View></View><View style={styles.week}>{weekBars.map((v,i)=><View key={i} style={styles.weekCol}><View style={[styles.weekBar,{height:Math.round(v*.65)}]}/><Txt variant="label" color={figma.muted}>{i+1}</Txt></View>)}</View></FCard>

      <SectionHeader title={lang==="ru"?"Мои препараты":"My medications"} action={`${active.length} ${lang==="ru"?"активных":"active"}`}/>
      <FCard style={{paddingVertical:4}}>{active.length?active.map((m,i)=><View key={m.id}>{i?<View style={mobileStyles.divider}/>:null}<Pressable testID={`medication-${m.id}`} onPress={()=>openEdit(m)} style={styles.medRow}><View style={styles.medIcon}><Ionicons name="medkit-outline" size={19} color={figma.ink}/></View><View style={{flex:1}}><View style={styles.medTitle}><Txt variant="caption" weight="bold">{m.name}</Txt>{m.dose?<Txt variant="label" color={figma.muted}>{m.dose}</Txt>:null}</View><Txt variant="label" color={figma.muted}>{(m.times||[]).join(" · ") || (lang==="ru"?"Расписание не задано":"No schedule")}{m.meal_relation?` · ${mealLabel(m.meal_relation,lang)}`:""}</Txt></View><Ionicons name="chevron-forward" size={18} color={figma.muted}/></Pressable></View>):<View style={styles.empty}><Txt variant="label" color={figma.muted}>{lang==="ru"?"Добавьте первый препарат":"Add your first medication"}</Txt></View>}</FCard>
      {taken.length?<><SectionHeader title={lang==="ru"?"Последние отметки":"Recent intakes"} action={lang==="ru"?"История ›":"History ›"}/><FCard style={{paddingVertical:4}}>{taken.slice(0,3).map((s:any,i)=><View key={s.id}>{i?<View style={mobileStyles.divider}/>:null}<View style={styles.recent}><View style={[styles.dot,{backgroundColor:figma.green}]}/><Txt variant="label" color={figma.muted} style={{flex:1}}>{dayjs(s.scheduled_at).format("D MMM · HH:mm")}</Txt><Txt variant="caption" weight="bold">{items.find(m=>m.id===s.medication_id)?.name||""}</Txt><Txt variant="label" color={figma.green}>{lang==="ru"?"Принято":"Taken"}</Txt></View></View>)}</FCard></>:null}
    </View></ScrollView>

    <Sheet visible={editorOpen} onClose={()=>setEditorOpen(false)} scroll testID="medication-editor-sheet">
      <Txt variant="h1" style={{fontSize:28}}>{editingId?(lang==="ru"?"Редактировать препарат":"Edit medication"):(lang==="ru"?"Добавить препарат":"Add medication")}</Txt><Txt variant="label" color={figma.muted} style={{marginTop:4,marginBottom:18}}>{lang==="ru"?"Название, дозировка, расписание и напоминания":"Name, dose, schedule and reminders"}</Txt>
      <Field label={lang==="ru"?"Название":"Name"} value={name} onChangeText={setName}/><View style={styles.fieldRow}><View style={{flex:1}}><Field label={lang==="ru"?"Дозировка":"Dose"} value={dose} onChangeText={setDose}/></View><View style={{flex:1}}><Field label={lang==="ru"?"Время":"Times"} value={timesText} onChangeText={setTimesText} placeholder="08:00, 20:00"/></View></View>
      <Txt variant="caption" weight="bold" style={{marginTop:8}}>{lang==="ru"?"Связь с едой":"Meal relation"}</Txt><View style={styles.meals}>{["any","before","with","after"].map(x=><Pressable key={x} onPress={()=>setMeal(x)} style={[styles.meal,meal===x&&styles.mealActive]}><Txt variant="label" color={meal===x?"#fff":figma.ink} weight="semibold">{mealLabel(x,lang)}</Txt></Pressable>)}</View>
      <Pressable onPress={save} disabled={saving||!name.trim()||parseTimes(timesText).some(t=>!TIME_RE.test(t))} style={[styles.save,(saving||!name.trim())&&{opacity:.5}]}><Txt variant="caption" color="#fff" weight="bold">{saving?"…":(lang==="ru"?"Сохранить препарат":"Save medication")}</Txt></Pressable>
      {editingId?<Pressable testID={`delete-medication-${editingId}`} onPress={()=>{void del(editingId);setEditorOpen(false);}} style={styles.delete}><Txt variant="caption" color="#B3261E" weight="bold">{lang==="ru"?"Удалить препарат":"Delete medication"}</Txt></Pressable>:null}
    </Sheet>
  </View>;
}
function Field(props:any){return <View style={{marginBottom:12}}><Txt variant="label" color={figma.muted} style={{marginBottom:6}}>{props.label}</Txt><TextInput {...props} placeholderTextColor={figma.muted} style={styles.input}/></View>}
function mealLabel(v:string,lang:string){const ru:any={any:"Неважно",before:"До еды",with:"Во время еды",after:"После еды"};const en:any={any:"Any time",before:"Before food",with:"With food",after:"After food"};return (lang==="ru"?ru:en)[v]||v;}

const styles=StyleSheet.create({header:{flexDirection:"row",alignItems:"center",gap:14},round:{width:40,height:40,borderRadius:20,backgroundColor:figma.card,alignItems:"center",justifyContent:"center"},title:{fontSize:27,lineHeight:31},loading:{minHeight:60,flexDirection:"row",alignItems:"center",gap:10},error:{marginTop:12,minHeight:54,borderRadius:20,backgroundColor:figma.card,padding:14,flexDirection:"row",alignItems:"center",gap:10},hero:{minHeight:192,position:"relative"},time:{fontSize:54,lineHeight:58,color:figma.ink,marginTop:7},heroAction:{height:34,alignSelf:"flex-start",marginTop:14,borderRadius:999,backgroundColor:figma.card,paddingHorizontal:16,alignItems:"center",justifyContent:"center"},sun:{position:"absolute",right:18,top:24,width:66,height:66,borderRadius:33,backgroundColor:"rgba(255,255,255,.55)",alignItems:"center",justifyContent:"center"},todayStack:{gap:10},slot:{minHeight:112,flexDirection:"row",alignItems:"center",gap:12},timePill:{width:58,height:36,borderRadius:18,backgroundColor:figma.bg,alignItems:"center",justifyContent:"center"},smallAction:{height:32,borderRadius:999,paddingHorizontal:12,backgroundColor:"#EEF2DB",alignItems:"center",justifyContent:"center"},adherence:{minHeight:190},adHead:{flexDirection:"row",alignItems:"flex-start",justifyContent:"space-between"},percent:{fontSize:42,lineHeight:46,color:figma.ink},week:{height:90,flexDirection:"row",alignItems:"flex-end",justifyContent:"space-between",marginTop:14},weekCol:{alignItems:"center",gap:5},weekBar:{width:22,borderRadius:11,backgroundColor:figma.ink},medRow:{minHeight:72,flexDirection:"row",alignItems:"center",gap:12},medIcon:{width:38,height:38,borderRadius:19,backgroundColor:"#FFF6D8",alignItems:"center",justifyContent:"center"},medTitle:{flexDirection:"row",alignItems:"center",gap:8,flexWrap:"wrap"},empty:{minHeight:90,alignItems:"center",justifyContent:"center"},recent:{minHeight:64,flexDirection:"row",alignItems:"center",gap:9},dot:{width:9,height:9,borderRadius:5},fieldRow:{flexDirection:"row",gap:10},input:{height:58,borderRadius:20,backgroundColor:figma.bg,paddingHorizontal:14,color:figma.ink,fontSize:16},meals:{flexDirection:"row",flexWrap:"wrap",gap:8,marginTop:10},meal:{height:36,borderRadius:999,backgroundColor:figma.bg,paddingHorizontal:12,alignItems:"center",justifyContent:"center"},mealActive:{backgroundColor:figma.ink},save:{height:62,borderRadius:999,backgroundColor:figma.ink,alignItems:"center",justifyContent:"center",marginTop:22},delete:{height:54,borderRadius:999,backgroundColor:"#FCE8E6",alignItems:"center",justifyContent:"center",marginTop:10}});
