import React, { useState } from 'react';
import { ArrowUpRight, Brain, CalendarDays, ChevronDown, CircleDot, FileText, HeartPulse, LockKeyhole, Pill, Sparkles, Stethoscope, TestTube2, TimerReset } from 'lucide-react';

interface Props { onStartQuestionnaire:()=>void; onGoToDashboard:()=>void; onLoginClick:()=>void; isAuthenticated:boolean; }
const LOGO='https://www.figma.com/api/mcp/asset/66db2519-49f5-41e3-acab-8e0517e9415a.png';
const DNA='https://www.figma.com/api/mcp/asset/bc034b94-f518-48ba-a44e-c7bfb79b9dfb.png';
const mods=[['Организм','Состояние систем и общая картина',HeartPulse],['Анализы','Показатели, документы и динамика',TestTube2],['Давление','Измерения давления и пульса',Stethoscope],['Психика','Настроение, стресс и дневник',Brain],['Лекарства','Расписание и отметки о приёме',Pill],['Женское здоровье','Цикл, симптомы и наблюдения',CalendarDays],['ИИ-ассистент Аида','Ответы по данным с источниками',Sparkles],['Задачи','Напоминания, визиты и план',TimerReset],['История здоровья','Единая хронология событий',FileText]] as const;
const faqs=[['Что такое Аида?','Цифровой ассистент, который объединяет данные здоровья, находит взаимосвязи и объясняет персональные наблюдения.'],['Это медицинский диагноз?','Нет. Аида помогает структурировать и объяснять данные, но не заменяет врача и не ставит диагноз.'],['Какие данные можно добавить?','Анализы, измерения, симптомы, лекарства, дневники, документы и данные подключённых устройств.'],['Как формируются выводы?','Аида использует только доступные данные профиля, показывает источники и прямо сообщает, если информации недостаточно.'],['Можно удалить данные?','Да. Пользователь контролирует доступы, экспорт и удаление своих данных.'],['Есть ли бесплатный доступ?','Начать работу с профилем можно бесплатно.']] as const;
export const PromoLanding:React.FC<Props>=({onStartQuestionnaire,onGoToDashboard,onLoginClick,isAuthenticated})=>{
 const [open,setOpen]=useState(0); const go=isAuthenticated?onGoToDashboard:onStartQuestionnaire;
 return <div className="min-h-screen bg-[#ecedef] text-[#061d48] font-['Manrope',Inter,sans-serif]">
  <div className="mx-auto flex max-w-[1440px] flex-col gap-[18px] p-3 sm:p-4 lg:p-6">
   <header className="sticky top-3 z-50 flex min-h-[76px] items-center justify-between rounded-[24px] bg-white px-5 py-3 shadow-[0_18px_45px_rgba(64,69,87,.10)] lg:min-h-[94px] lg:px-[30px]">
    <img src={LOGO} alt="Аида" className="h-12 w-auto max-w-[170px] object-contain lg:h-20 lg:max-w-[220px]" />
    <nav className="hidden gap-7 text-[12px] font-semibold text-[#616471] lg:flex"><a href="#advantages">Преимущества</a><a href="#difference">Отличия</a><a href="#how">Как работает</a><a href="#modules">Функционал</a><a href="#faq">FAQ</a></nav>
    <div className="flex items-center gap-2">{!isAuthenticated&&<button onClick={onLoginClick} className="hidden px-3 py-2 text-[12px] font-bold sm:block">Войти</button>}<button onClick={go} className="rounded-[14px] bg-[#e9294f] px-4 py-3 text-[11px] font-bold text-white">{isAuthenticated?'Открыть профиль ↗':'Начать бесплатно ↗'}</button></div>
   </header>
   <section className="grid overflow-hidden rounded-[36px] bg-white shadow-[0_30px_80px_rgba(64,69,87,.15)] lg:min-h-[720px] lg:grid-cols-[46%_54%]">
    <div className="px-6 py-10 sm:px-10 lg:px-[68px] lg:py-[82px]"><div className="inline-flex h-[34px] items-center gap-2 rounded-full border border-[#e9294f]/20 px-3.5 text-[9px] font-bold text-[#e9294f]"><span className="size-[7px] rounded-full bg-[#e9294f]"/>ЦИФРОВОЙ АССИСТЕНТ ЗДОРОВЬЯ</div><h1 className="mt-6 max-w-[580px] text-[44px] font-bold leading-[.98] tracking-[-.055em] text-[#171824] sm:text-[58px] lg:text-[68px]">Цифровой ассистент здоровья нового поколения.</h1><p className="mt-6 max-w-[540px] text-[14px] leading-[1.75] text-[#73757f]">Аида объединяет медицинские данные, ежедневное самочувствие и назначения в понятный профиль — чтобы замечать взаимосвязи, видеть динамику и лучше понимать свой организм.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><button onClick={go} className="rounded-[14px] bg-[#e9294f] px-5 py-4 text-[12px] font-bold text-white">{isAuthenticated?'Открыть цифровой профиль ↗':'Начать бесплатно ↗'}</button><button onClick={isAuthenticated?onGoToDashboard:onLoginClick} className="rounded-[14px] bg-[#f2f3f6] px-5 py-4 text-[12px] font-bold text-[#171824]">{isAuthenticated?'Открыть интерфейс':'Попробовать демо-интерфейс'}</button></div><div className="mt-6 flex flex-wrap gap-7 text-[10px] text-[#8e909a]"><span>◉ Без выдуманных показателей</span><span>▣ Данные под вашим контролем</span></div></div>
    <div className="relative min-h-[560px] overflow-hidden bg-[#f5f6f8] lg:min-h-[720px]"><div className="absolute left-1/2 top-1/2 size-[72%] -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#e3e5ea]"/><div className="absolute left-1/2 top-1/2 size-[58%] -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#e9294f]/25"/><img src={DNA} alt="3D ДНК" className="absolute left-1/2 top-1/2 h-[88%] w-[54%] -translate-x-1/2 -translate-y-1/2 object-contain drop-shadow-[0_28px_24px_rgba(38,41,51,.20)]"/>{[['СОСТОЯНИЕ','Нет данных','right-[6%] top-[10%]'],['01 / БИОМАРКЕРЫ','Единая динамика','left-[4%] top-[42%]'],['AIDA / СВОДКА','ИИ-итог дня','bottom-[10%] right-[4%]']].map(([a,b,p])=><div key={a} className={`absolute ${p} rounded-[16px] bg-white px-4 py-3 shadow-[0_14px_30px_rgba(56,61,77,.14)]`}><div className="text-[8px] font-bold text-[#979aa5]">{a}</div><div className="mt-1 text-[12px] font-semibold">{b}</div></div>)}</div>
   </section>
   <section id="advantages" className="grid gap-8 px-2 py-16 lg:grid-cols-[430px_1fr] lg:gap-[70px] lg:px-7 lg:py-[100px]"><div><p className="text-[9px] font-bold text-[#8e909a]">01 / ПРЕИМУЩЕСТВА</p><h2 className="mt-5 text-[42px] font-semibold leading-none tracking-[-.05em] sm:text-[56px]">Всё важное<br/>собрано вместе.</h2><p className="mt-6 max-w-[390px] text-[13px] leading-[1.75] text-[#73757f]">От первой загрузки анализа до ежедневных наблюдений — без разрозненных таблиц и медицинского шума.</p></div><div className="grid gap-4 sm:grid-cols-2">{[['Единый профиль здоровья','Все сведения складываются в целостную цифровую картину.'],['Все данные в одном месте','Анализы, симптомы, давление, психика, лекарства и цикл.'],['Персональный анализ','Аида работает с вашей историей и отделяет факты от предположений.'],['Отслеживание динамики','Изменения становятся заметны во времени.']].map(([t,d],i)=><article key={t} className="rounded-[24px] bg-[#f7f8fa] p-6 shadow-[0_18px_38px_rgba(64,69,87,.10)]"><div className="text-[9px] font-bold text-[#e9294f]">0{i+1}</div><div className="mt-4 flex size-12 items-center justify-center rounded-full bg-white shadow"><CircleDot className="size-5 text-[#e9294f]"/></div><h3 className="mt-4 text-[18px] font-semibold">{t}</h3><p className="mt-3 text-[11px] leading-[1.6] text-[#73757f]">{d}</p></article>)}</div></section>
   <section id="difference" className="rounded-[34px] bg-[#f7f8fa] px-6 py-12 shadow-[0_25px_60px_rgba(64,69,87,.12)] sm:px-10 lg:px-[68px]"><p className="text-[9px] font-bold text-[#8e909a]">02 / ГЛАВНОЕ ОТЛИЧИЕ</p><h2 className="mt-5 text-[40px] font-semibold leading-none tracking-[-.05em] sm:text-[60px]">Аида видит не отдельные цифры,<br className="hidden sm:block"/> а связи между ними.</h2><p className="mt-6 max-w-[760px] text-[13px] leading-[1.75] text-[#73757f]">Аида объединяет разные типы данных, учитывает их последовательность и объясняет, что именно повлияло на персональное наблюдение.</p><div className="relative mx-auto my-10 h-[430px] max-w-[1100px]"><div className="absolute left-1/2 top-1/2 size-[390px] -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#dfe2e8]"/><div className="absolute left-1/2 top-1/2 size-[300px] -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#e9294f]/25"/><div className="absolute left-1/2 top-1/2 flex size-[190px] -translate-x-1/2 -translate-y-1/2 flex-col items-center justify-center rounded-full bg-white shadow-[0_20px_38px_rgba(64,69,87,.17)]"><CircleDot className="size-8 text-[#e9294f]"/><b className="mt-2 text-[15px]">Единый профиль</b><span className="mt-1 text-[8px] text-[#9a9ca5]">ваша история здоровья</span></div>{[['Анализы','left-1/2 top-0 -translate-x-1/2'],['Симптомы','right-[3%] top-[20%]'],['Давление','right-0 bottom-[18%]'],['Психика','left-1/2 bottom-0 -translate-x-1/2'],['Лекарства','left-0 bottom-[18%]'],['Цикл','left-[3%] top-[20%]']].map(([x,p])=><div key={x} className={`absolute ${p} rounded-full bg-white px-7 py-4 text-[10px] font-semibold text-[#555864] shadow`}>{x}</div>)}</div><div className="grid gap-5 md:grid-cols-3">{[['01','Связывает разные данные','Находит изменения между дневниками.'],['02','Учитывает личную историю','Выводы строятся на ваших наблюдениях.'],['03','Объясняет каждый вывод','Показывает источники и факторы.']].map(([n,t,d])=><div key={n} className="border-t border-[#d9dce2] pt-4"><span className="text-[8px] font-bold text-[#e9294f]">{n}</span><h3 className="mt-3 text-[14px] font-semibold">{t}</h3><p className="mt-2 text-[10px] text-[#858893]">{d}</p></div>)}</div></section>
   <section id="how" className="grid rounded-[34px] bg-[#06152f] px-6 py-12 text-white shadow-[0_30px_68px_rgba(5,20,46,.25)] sm:px-10 lg:grid-cols-[535px_1fr] lg:gap-20 lg:px-[70px]"><div className="flex flex-col justify-center"><p className="text-[9px] font-bold text-[#fa5571]">03 / КАК ЭТО РАБОТАЕТ</p><h2 className="mt-5 text-[42px] font-semibold leading-none tracking-[-.05em] sm:text-[58px]">Пять шагов<br/>к ясной картине.</h2><p className="mt-6 max-w-[430px] text-[12px] leading-[1.75] text-[#adb5c7]">Профиль развивается вместе с вами: чем больше собственных данных, тем точнее становится динамика.</p><button onClick={go} className="mt-7 w-fit rounded-[14px] bg-[#e9294f] px-5 py-4 text-[11px] font-bold">Открыть цифровой профиль ↗</button></div><div className="mt-8 lg:mt-0">{['Добавление анализов, измерений и записей','Объединение сведений в единый профиль','Анализ взаимосвязей между событиями','Формирование персональных наблюдений','Отслеживание изменений во времени'].map((x,i)=><div key={x} className="flex min-h-[92px] items-center gap-6 border-t border-white/15 last:border-b"><span className="text-[10px] font-bold text-[#fa5571]">0{i+1}</span><span className="text-[15px] text-[#d6dae4]">{x}</span></div>)}</div></section>
   <section id="modules" className="px-2 py-16 lg:px-7 lg:py-[100px]"><div className="text-center"><p className="text-[9px] font-bold text-[#8e909a]">04 / ФУНКЦИОНАЛ</p><h2 className="mt-4 text-[36px] font-semibold tracking-[-.05em] sm:text-[56px]">Один профиль. Девять связанных разделов.</h2><p className="mt-4 text-[12px] text-[#777a85]">Каждый модуль работает самостоятельно и дополняет общую картину здоровья.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{mods.map(([t,d,I],i)=><article key={t} className="rounded-[23px] bg-[#f7f8fa] p-6 shadow-[0_17px_34px_rgba(64,69,87,.10)]"><div className="flex items-center justify-between"><div className="flex size-12 items-center justify-center rounded-full bg-white shadow"><I className="size-5 text-[#e9294f]"/></div><span className="text-[8px] font-bold text-[#bfc1c8]">{String(i+1).padStart(2,'0')}</span></div><h3 className="mt-4 text-[17px] font-semibold">{t}</h3><p className="mt-3 text-[10px] text-[#858893]">{d}</p></article>)}</div></section>
   <section className="grid rounded-[30px] bg-[#06152f] px-6 py-8 text-center sm:grid-cols-4">{[[9,'связанных разделов'],[1,'единый профиль здоровья'],[5,'этапов персонального анализа'],[0,'выдуманных показателей']].map(([v,l])=><div key={String(l)} className="py-6"><div className="text-[64px] font-bold text-[#fa4264]">{v}</div><div className="text-[10px] text-[#c9ceda]">{l}</div></div>)}</section>
   <section className="rounded-[34px] bg-[#f6f7fa] px-6 py-12 lg:px-[60px]"><div className="inline-flex rounded-full bg-white px-5 py-3 text-[12px] font-semibold text-[#e9294f]">ОТЗЫВЫ И СЦЕНАРИИ</div><div className="mt-6 grid gap-5 lg:grid-cols-2"><h2 className="text-[38px] font-medium leading-[1.2] tracking-[-.04em] text-[#0e0f1b] sm:text-[48px]">Аида помогает видеть здоровье целиком</h2><p className="text-[15px] text-[#6b7080]">Показываем примеры взаимодействия — без вымышленных медицинских обещаний.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{['Я наконец вижу, как сон и стресс связаны с моим самочувствием.','После анализов Аида объяснила, какие показатели требуют внимания.','Напоминания и история помогают не терять важные наблюдения.'].map(x=><article key={x} className="rounded-[26px] bg-white p-7 shadow"><div className="text-[52px] text-[#f06b68]">“</div><p className="text-[18px] font-medium text-[#0e0f1b]">«{x}»</p><div className="mt-10 text-[12px] font-semibold text-[#6b7080]">Пример сценария · пользователь</div></article>)}</div></section>
   <section className="grid rounded-[34px] bg-white px-6 py-12 lg:grid-cols-[1fr_420px] lg:px-[60px]"><div><span className="rounded-full bg-[#f6f7fa] px-5 py-3 text-[12px] font-semibold text-[#e9294f]">БЕЗОПАСНОСТЬ</span><h2 className="mt-8 text-[42px] font-medium leading-[1.15] text-[#0e0f1b] sm:text-[50px]">Ваши данные —<br/>только ваши.</h2><p className="mt-7 max-w-[560px] text-[16px] text-[#6b7080]">Аида создаёт единый профиль здоровья с уважением к конфиденциальности и полным контролем пользователя.</p><div className="mt-10 flex flex-wrap gap-3">{['Контроль доступа','Прозрачные выводы','История изменений'].map(x=><span key={x} className="rounded-full bg-[#f6f7fa] px-5 py-3 text-[12px] font-semibold">{x}</span>)}</div></div><div className="flex min-h-[320px] items-center justify-center"><div className="flex size-[170px] items-center justify-center rounded-full bg-[#f8f9fb] shadow"><LockKeyhole className="size-16"/></div></div></section>
   <section id="faq" className="grid gap-10 rounded-[34px] bg-[#f6f7fa] px-6 py-12 lg:grid-cols-[430px_1fr] lg:px-[60px]"><div><span className="rounded-full bg-white px-5 py-3 text-[12px] font-semibold text-[#e9294f]">FAQ</span><h2 className="mt-8 text-[42px] font-medium text-[#0e0f1b] sm:text-[48px]">Вопросы об Аиде</h2><p className="mt-5 text-[16px] text-[#6b7080]">Коротко о данных, подключении и возможностях сервиса.</p></div><div className="space-y-3">{faqs.map(([q,a],i)=><button key={q} onClick={()=>setOpen(open===i?-1:i)} className="w-full rounded-[20px] bg-white p-6 text-left"><div className="flex justify-between"><b className="text-[17px] text-[#0e0f1b]">{q}</b><ChevronDown className={`size-5 text-[#e9294f] ${open===i?'rotate-180':''}`}/></div>{open===i&&<p className="mt-4 text-[13px] leading-[1.6] text-[#6b7080]">{a}</p>}</button>)}</div></section>
   <section className="relative overflow-hidden rounded-[34px] bg-[#061d48] px-6 py-12 text-white lg:px-[60px]"><div className="absolute -right-12 top-1/2 size-[330px] -translate-y-1/2 rounded-full bg-[radial-gradient(circle,rgba(233,41,79,.55),transparent_68%)] blur-xl"/><div className="relative grid gap-8 lg:grid-cols-2"><div><span className="rounded-full bg-[#142957] px-5 py-3 text-[12px] font-semibold text-[#f06b68]">АИДА РЯДОМ</span><h2 className="mt-8 text-[40px] font-medium leading-[1.18] sm:text-[49px]">Начните понимать<br/>своё здоровье сегодня.</h2></div><div><p className="text-[16px] text-[#bfcce5]">Соберите первый цифровой профиль — бесплатно.</p><button onClick={go} className="mt-7 rounded-[20px] bg-[#e9294f] px-7 py-5 text-[15px] font-semibold">Начать бесплатно <ArrowUpRight className="ml-2 inline size-4"/></button></div></div></section>
   <footer className="rounded-[34px] bg-white px-6 py-10 lg:px-[60px]"><div className="grid gap-8 md:grid-cols-[1fr_220px_1fr]"><div><div className="text-[30px] font-medium">Аида</div><div className="mt-4 text-[12px] font-semibold"><span className="mr-2 inline-block size-3 rounded-full bg-[#e9294f]"/>ваше здоровье • единая система</div></div><div className="space-y-3 text-[13px] text-[#6b7080]"><a className="block" href="#advantages">Преимущества</a><a className="block" href="#how">Как это работает</a><a className="block" href="#modules">Функционал</a><a className="block" href="#faq">FAQ</a></div><div className="space-y-3 text-[13px] text-[#6b7080]"><div>Политика конфиденциальности</div><div>Пользовательское соглашение</div><div>Контакты</div></div></div><div className="mt-8 border-t border-[#e0e5f0] pt-5 text-[11px] text-[#6b7080]">© 2026 Аида. Информация в сервисе не заменяет консультацию врача.</div></footer>
  </div>
 </div>
}
